name: Docker Image Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Flask backend Docker image
      uses: docker/build-push-action@v1
      with:
        context: .
        dockerfile: ./Dockerfile.flask
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest

    - name: Build and push Vue.js frontend Docker image
      uses: docker/build-push-action@v1
      with:
        context: .
        dockerfile: ./Dockerfile.vue
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/vue-frontend:latest

