name: Build Docker image

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check if secret is set
      run: |
        secrets=("PORT_TEST", "ASD")
        for secret in "${secrets[@]}"
        do
          if [[ -z "${{ secrets.${secret} }}" ]]; then
            echo "${secret} not set!"
            exit 1
          else
            echo "${secret} set!"
          fi
        done

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: justsnaf/flask-test:latest
