name: Docker Image Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Secret check
      run: |
        if [[ -z "${{ secrets.HOST_PORT }}" ]]; then
          echo "Host port secret not set or invalid"
          exit 1
        else
          echo "HOST_PORT=${{ secrets.HOST_PORT }}" >> .env
        fi

        if [[ -z "${{ secrets.HOST_ADDRESS }}" ]]; then
          echo "Host address secret not set or invalid"
          exit 1
        else
          echo "HOST_ADDRESS=${{ secrets.HOST_ADDRESS }}" >> .env
        fi

        if [[ -z "${{ secrets.DATABASE_URL }}" ]]; then
          echo "Database URL not set or invalid"
          exit 1
        else
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
        fi


    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-rest-temp:latest
