name: Build Electron App

on:
  push:
    branches:
      - main # Replace with the name of your default branch if different

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can use other Node.js versions as well

    - name: Install dependencies
      run: npm ci

    - name: Build and package Electron app
      run: |
        npm install electron-packager -g
        electron-packager . --platform=win32 --arch=x64 --asar --out=dist --overwrite

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: dist/*.exe
