name: Build Electron App

on:
  push:
    branches:
      - main # Replace with the name of your default branch if different

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # You can use other Node.js versions as well

    - name: Install dependencies
      run: npm ci
      working-directory: desktop

    - name: Build and package Electron app
      run: npm run build
      working-directory: desktop
      
    - name: List contents of working directory
      run: Get-ChildItem -Name
      working-directory: desktop

    - name: Display electron-packager command output
      run: |
        npm install electron-packager -g
        electron-packager . --platform=win32 --arch=x64 --asar --out=dist --overwrite --debug
      working-directory: desktop
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: desktop/dist/*.exe # Update the artifact path

    - name: List contents of dist directory
      run: Get-ChildItem -Path desktop/dist

    - name: Install and authenticate with GitHub CLI
      run: |
        Invoke-WebRequest -Uri "https://github.com/cli/cli/releases/download/v2.28.0/gh_2.28.0_windows_amd64.zip" -OutFile "gh.zip"
        Expand-Archive -Path "gh.zip" -DestinationPath "gh"
        $Env:Path += ";$(Get-Location)\gh\bin"
        echo ${{ secrets.PAT }} | gh auth login --with-token

    - name: Delete existing release and tag if exist
      run: |
        gh release delete v1.0.0 -d --yes || echo "No existing release found"
        git push -d --verbose origin v1.0.0 || echo "No existing tag found"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}


    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        body: Description of the release
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./desktop/dist/Your App Name-Setup-1.0.0.exe
        asset_name: Your App Name-Setup-1.0.0.exe
        asset_content_type: application/octet-stream
