name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: desktop

    - name: Build and package Electron app
      run: npm run build
      working-directory: desktop

    - name: Display electron-packager command output
      run: |
        npm install electron-packager -g
        electron-packager . --platform=win32 --arch=x64 --asar --out=dist --overwrite --debug
      working-directory: desktop

    - name: Delete existing release (if exists)
      run: |
        gh release delete v1.0.0 --yes || true
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Create Release
      run: |
        gh release create v1.0.0 --title "Release v1.0.0" --notes "Please IGNORE the 'Source code (zip)' and 'Source code (tar.gz)' assets. Download 'Your App Name-Setup-1.0.0.exe' to get the latest version of the application."
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Fetch Release ID
      run: |
        echo "RELEASE_ID=$(gh api repos/:owner/:repo/releases/tags/v1.0.0 --jq '.id')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Update Release (remove source code assets)
      run: |
        gh api repos/:owner/:repo/releases/:release_id --method PATCH --field tarball_url= --field zipball_url=
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        RELEASE_ID: ${{ env.RELEASE_ID }}

    - name: Fetch Release
      run: |
        echo "UPLOAD_URL=$(gh api repos/:owner/:repo/releases/tags/v1.0.0 --jq '.upload_url')" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./desktop/dist/Your App Name-Setup-1.0.0.exe
        asset_name: Your App Name-Setup-1.0.0.exe
        asset_content_type: application/octet-stream
